"""Hybrid search + SQL tiebreaker — Milvus 2.5 multi-vector path.

Milvus hybrid search (text_dense + text_sparse BM25 + visual_dense).

Three lanes: text_dense (gemini-embedding-2 @768) + text_sparse (BM25
auto-generated by Milvus) + visual_dense (gemini-embedding-2 multimodal).
Fused via RRFRanker. SQL tiebreaker re-orders by confidence + start_sec.
"""
from __future__ import annotations

from typing import Any


async def hybrid_search(
    client: Any,
    collection: str,
    query_text: str,
    query_dense_text: list[float],
    query_dense_visual: list[float] | None = None,
    top_k: int = 32,
) -> list[dict]:
    """Hybrid multi-vector retrieval against Milvus.

    Returns ordered list of hit dicts with evidence_id, channel, start_sec,
    end_sec, claim_text fields. Caller does SQL tiebreaker on the result.
    """
    # TODO: implement using pymilvus AnnSearchRequest + RRFRanker
    return []


async def sql_tiebreak(evidence_ids: list[str], session: Any) -> list[dict]:
    """Re-order Milvus hit ids by Postgres confidence + start_sec.

    SQL tiebreaker fragment:
        SELECT * FROM evidence_claims
        WHERE id = ANY($1)
        ORDER BY array_position($1::varchar[], id),
                 CASE confidence WHEN 'clear' THEN 3 WHEN 'blurry' THEN 2
                                 WHEN 'inferred' THEN 1 ELSE 0 END DESC,
                 start_sec ASC
    """
    # TODO: implement
    return []
