"""Collection schema for per-ingest video collections.

Milvus collection schema builder + creation helper.

Default strategy: one collection per ingest (urusai_v_<ingest_id>).
Escape hatch: single collection per workspace with
ingest_id partition key — switch by changing build_video_collection_schema
arguments; client code untouched.
"""
from __future__ import annotations

from typing import Any


def build_video_collection_schema(client: Any, *, with_partition_key: bool = False) -> Any:
    """Build the multi-vector schema for one video collection.

    Fields:
    - evidence_id          VARCHAR(36) PRIMARY
    - channel              VARCHAR(32)
    - start_sec / end_sec  FLOAT
    - claim_text           VARCHAR(2048) analyzer + match (for BM25 input)
    - text_dense           FLOAT_VECTOR dim=768 (gemini-embedding-2)
    - text_sparse          SPARSE_FLOAT_VECTOR (auto-generated by BM25 function)
    - visual_dense         FLOAT_VECTOR dim=768 (gemini-embedding-2 keyframe)
    - ingest_id (optional) VARCHAR(64) partition key, only when with_partition_key=True
    """
    from pymilvus import DataType, Function, FunctionType

    schema = client.create_schema(auto_id=False, enable_dynamic_field=True)
    schema.add_field("evidence_id", DataType.VARCHAR, max_length=36, is_primary=True)
    schema.add_field("channel", DataType.VARCHAR, max_length=32)
    schema.add_field("start_sec", DataType.FLOAT)
    schema.add_field("end_sec", DataType.FLOAT)
    schema.add_field(
        "claim_text",
        DataType.VARCHAR,
        max_length=2048,
        enable_analyzer=True,
        enable_match=True,
    )
    schema.add_field("text_dense", DataType.FLOAT_VECTOR, dim=768)
    schema.add_field("text_sparse", DataType.SPARSE_FLOAT_VECTOR)
    schema.add_field("visual_dense", DataType.FLOAT_VECTOR, dim=768)

    if with_partition_key:
        schema.add_field(
            "ingest_id",
            DataType.VARCHAR,
            max_length=64,
            is_partition_key=True,
        )

    schema.add_function(
        Function(
            name="text_bm25",
            function_type=FunctionType.BM25,
            input_field_names=["claim_text"],
            output_field_names=["text_sparse"],
        )
    )
    return schema


def collection_name_for(ingest_id: str) -> str:
    """Canonical Milvus collection name for one ingest."""
    return f"urusai_v_{ingest_id}"


def ensure_video_collection(
    client: Any,
    ingest_id: str,
    *,
    with_partition_key: bool = False,
) -> str:
    """Create the per-ingest Milvus collection if missing; return its name.

    Idempotent. Indexes match the multi-vector hybrid search retriever:
    text_dense + visual_dense use AUTOINDEX with IP metric; text_sparse uses
    SPARSE_INVERTED_INDEX with BM25 metric (the BM25 Function in the schema
    populates text_sparse automatically from claim_text on insert).
    """
    name = collection_name_for(ingest_id)
    if client.has_collection(collection_name=name):
        return name
    schema = build_video_collection_schema(
        client, with_partition_key=with_partition_key
    )
    index_params = client.prepare_index_params()
    index_params.add_index(
        "text_dense", index_type="AUTOINDEX", metric_type="IP"
    )
    index_params.add_index(
        "text_sparse",
        index_type="SPARSE_INVERTED_INDEX",
        metric_type="BM25",
    )
    index_params.add_index(
        "visual_dense", index_type="AUTOINDEX", metric_type="IP"
    )
    client.create_collection(
        collection_name=name,
        schema=schema,
        index_params=index_params,
    )
    return name
