"""Collection schema for per-ingest video collections.

Milvus collection schema builder + creation helper.

Default strategy: one collection per ingest (urusai_v_<ingest_id>).
Escape hatch: single collection per workspace with
ingest_id partition key — switch by changing build_video_collection_schema
arguments; client code untouched.
"""
from __future__ import annotations

from typing import Any


def build_video_collection_schema(client: Any, *, with_partition_key: bool = False) -> Any:
    """Build the multi-vector schema for one video collection.

    Fields:
    - evidence_id          VARCHAR(36) PRIMARY
    - channel              VARCHAR(32)
    - start_sec / end_sec  FLOAT
    - claim_text           VARCHAR(2048) analyzer + match (for BM25 input)
    - text_dense           FLOAT_VECTOR dim=768 (gemini-embedding-2)
    - text_sparse          SPARSE_FLOAT_VECTOR (auto-generated by BM25 function)
    - visual_dense         FLOAT_VECTOR dim=768 (gemini-embedding-2 keyframe)
    - ingest_id (optional) VARCHAR(64) partition key, only when with_partition_key=True
    """
    from pymilvus import DataType, Function, FunctionType

    schema = client.create_schema(auto_id=False, enable_dynamic_field=True)
    schema.add_field("evidence_id", DataType.VARCHAR, max_length=36, is_primary=True)
    schema.add_field("channel", DataType.VARCHAR, max_length=32)
    schema.add_field("start_sec", DataType.FLOAT)
    schema.add_field("end_sec", DataType.FLOAT)
    schema.add_field(
        "claim_text",
        DataType.VARCHAR,
        max_length=2048,
        enable_analyzer=True,
        enable_match=True,
    )
    schema.add_field("text_dense", DataType.FLOAT_VECTOR, dim=768)
    schema.add_field("text_sparse", DataType.SPARSE_FLOAT_VECTOR)
    schema.add_field("visual_dense", DataType.FLOAT_VECTOR, dim=768)

    if with_partition_key:
        schema.add_field(
            "ingest_id",
            DataType.VARCHAR,
            max_length=64,
            is_partition_key=True,
        )

    schema.add_function(
        Function(
            name="text_bm25",
            function_type=FunctionType.BM25,
            input_field_names=["claim_text"],
            output_field_names=["text_sparse"],
        )
    )
    return schema
